### PR TITLE
Merge in M8 release branch

### PR DESCRIPTION
**Pull request by adagys**

### CODE REVIEW

**Comment by joeldudleyr3** [comment]
I'll clone and test it now.

**Comment by adagys** [comment]
Sorry, this won't work until https://github.com/corda/corda/pull/224 is merged

**Comment by joeldudleyr3** [comment]
Oh. Will I need to check out that branch and install, or is it on maven already?

**Comment by adagys** [comment]
Actually, yeah you could just checkout that branch & install, should work. It's back to SNAPSHOT, so that won't be published to maven

**Pull request merged**
